// Generated by gencpp from file crazyflie_driver/controllerFlag.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_CONTROLLERFLAG_H
#define CRAZYFLIE_DRIVER_MESSAGE_CONTROLLERFLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyflie_driver
{
template <class ContainerAllocator>
struct controllerFlag_
{
  typedef controllerFlag_<ContainerAllocator> Type;

  controllerFlag_()
    : controllerFlag(false)  {
    }
  controllerFlag_(const ContainerAllocator& _alloc)
    : controllerFlag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _controllerFlag_type;
  _controllerFlag_type controllerFlag;





  typedef boost::shared_ptr< ::crazyflie_driver::controllerFlag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie_driver::controllerFlag_<ContainerAllocator> const> ConstPtr;

}; // struct controllerFlag_

typedef ::crazyflie_driver::controllerFlag_<std::allocator<void> > controllerFlag;

typedef boost::shared_ptr< ::crazyflie_driver::controllerFlag > controllerFlagPtr;
typedef boost::shared_ptr< ::crazyflie_driver::controllerFlag const> controllerFlagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie_driver::controllerFlag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crazyflie_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'crazyflie_driver': ['/home/hiro/crazyflie_ros/src/crazyflie_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_driver::controllerFlag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_driver::controllerFlag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_driver::controllerFlag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "faacf4a6fc7c08bf15b15c2e29104501";
  }

  static const char* value(const ::crazyflie_driver::controllerFlag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfaacf4a6fc7c08bfULL;
  static const uint64_t static_value2 = 0x15b15c2e29104501ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie_driver/controllerFlag";
  }

  static const char* value(const ::crazyflie_driver::controllerFlag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool controllerFlag\n\
";
  }

  static const char* value(const ::crazyflie_driver::controllerFlag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controllerFlag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct controllerFlag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie_driver::controllerFlag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie_driver::controllerFlag_<ContainerAllocator>& v)
  {
    s << indent << "controllerFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.controllerFlag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_CONTROLLERFLAG_H
